// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: moderation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Text
type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // for tracing
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                      // model version hint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TextRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToxicityScore float64                `protobuf:"fixed64,1,opt,name=toxicity_score,json=toxicityScore,proto3" json:"toxicity_score,omitempty"`
	Flagged       bool                   `protobuf:"varint,2,opt,name=flagged,proto3" json:"flagged,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *TextResponse) GetToxicityScore() float64 {
	if x != nil {
		return x.ToxicityScore
	}
	return 0
}

func (x *TextResponse) GetFlagged() bool {
	if x != nil {
		return x.Flagged
	}
	return false
}

func (x *TextResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

// Image (bytes for simplicity)
type ImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageBytes    []byte                 `protobuf:"bytes,1,opt,name=image_bytes,json=imageBytes,proto3" json:"image_bytes,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_moderation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{2}
}

func (x *ImageRequest) GetImageBytes() []byte {
	if x != nil {
		return x.ImageBytes
	}
	return nil
}

func (x *ImageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ImageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsfwScore     float64                `protobuf:"fixed64,1,opt,name=nsfw_score,json=nsfwScore,proto3" json:"nsfw_score,omitempty"`
	Flagged       bool                   `protobuf:"varint,2,opt,name=flagged,proto3" json:"flagged,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	mi := &file_moderation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{3}
}

func (x *ImageResponse) GetNsfwScore() float64 {
	if x != nil {
		return x.NsfwScore
	}
	return 0
}

func (x *ImageResponse) GetFlagged() bool {
	if x != nil {
		return x.Flagged
	}
	return false
}

func (x *ImageResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

var File_moderation_proto protoreflect.FileDescriptor

const file_moderation_proto_rawDesc = "" +
	"\n" +
	"\x10moderation.proto\x12\rmoderation.v1\"Z\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"t\n" +
	"\fTextResponse\x12%\n" +
	"\x0etoxicity_score\x18\x01 \x01(\x01R\rtoxicityScore\x12\x18\n" +
	"\aflagged\x18\x02 \x01(\bR\aflagged\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"h\n" +
	"\fImageRequest\x12\x1f\n" +
	"\vimage_bytes\x18\x01 \x01(\fR\n" +
	"imageBytes\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"m\n" +
	"\rImageResponse\x12\x1d\n" +
	"\n" +
	"nsfw_score\x18\x01 \x01(\x01R\tnsfwScore\x12\x18\n" +
	"\aflagged\x18\x02 \x01(\bR\aflagged\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion2\xa6\x01\n" +
	"\x11ModerationService\x12F\n" +
	"\vPredictText\x12\x1a.moderation.v1.TextRequest\x1a\x1b.moderation.v1.TextResponse\x12I\n" +
	"\fPredictImage\x12\x1b.moderation.v1.ImageRequest\x1a\x1c.moderation.v1.ImageResponseBCZAgithub.com/Michaelc322/GoLang-Content-Moderation/go-gateway/pb;pbb\x06proto3"

var (
	file_moderation_proto_rawDescOnce sync.Once
	file_moderation_proto_rawDescData []byte
)

func file_moderation_proto_rawDescGZIP() []byte {
	file_moderation_proto_rawDescOnce.Do(func() {
		file_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_proto_rawDesc), len(file_moderation_proto_rawDesc)))
	})
	return file_moderation_proto_rawDescData
}

var file_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_moderation_proto_goTypes = []any{
	(*TextRequest)(nil),   // 0: moderation.v1.TextRequest
	(*TextResponse)(nil),  // 1: moderation.v1.TextResponse
	(*ImageRequest)(nil),  // 2: moderation.v1.ImageRequest
	(*ImageResponse)(nil), // 3: moderation.v1.ImageResponse
}
var file_moderation_proto_depIdxs = []int32{
	0, // 0: moderation.v1.ModerationService.PredictText:input_type -> moderation.v1.TextRequest
	2, // 1: moderation.v1.ModerationService.PredictImage:input_type -> moderation.v1.ImageRequest
	1, // 2: moderation.v1.ModerationService.PredictText:output_type -> moderation.v1.TextResponse
	3, // 3: moderation.v1.ModerationService.PredictImage:output_type -> moderation.v1.ImageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moderation_proto_init() }
func file_moderation_proto_init() {
	if File_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_proto_rawDesc), len(file_moderation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_proto_goTypes,
		DependencyIndexes: file_moderation_proto_depIdxs,
		MessageInfos:      file_moderation_proto_msgTypes,
	}.Build()
	File_moderation_proto = out.File
	file_moderation_proto_goTypes = nil
	file_moderation_proto_depIdxs = nil
}
